// Merge example: walk a route tree, generate a fresh spec, then layer it
// onto a hand-tuned `openapi.yaml` baseline using goai.Merge3Way. The
// hand-tuned content always wins; auto-discovered routes and schemas only
// fill gaps.
//
//	go run ./goai/examples/merge
//
// This is the canonical pattern when the project keeps a curated spec as
// the source of truth (rich descriptions, examples, x-* extensions) and
// wants the generator to surface only newly added endpoints.
package main

import (
	"fmt"
	"os"

	"github.com/yetiz-org/gone/channel"
	"github.com/yetiz-org/gone/ghttp"
	"github.com/yetiz-org/gone/goai"
)

const handTunedBaseline = `openapi: 3.0.3
info:
  title: Merge Example API
  description: Hand-curated description that survives the merge.
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Production
tags:
  - name: Public
    description: Hand-tuned tag description.
paths:
  /hello:
    get:
      summary: Hand-tuned summary for an existing route.
      description: |-
        This long-form description is hand-curated. The generator does not
        overwrite it on subsequent runs.
      tags:
        - Public
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world
components: {}
`

// HelloHandler is an existing endpoint already documented in the baseline.
type HelloHandler struct {
	ghttp.DefaultHTTPHandlerTask
}

func (h *HelloHandler) Get(ctx channel.HandlerContext, req *ghttp.Request, resp *ghttp.Response, params map[string]any) ghttp.ErrorResponse {
	resp.JsonResponse(map[string]string{"message": "Hello, world"})

	return nil
}

// NewHandler is a brand-new route that the baseline knows nothing about.
type NewHandler struct {
	ghttp.DefaultHTTPHandlerTask
}

func (h *NewHandler) Get(ctx channel.HandlerContext, req *ghttp.Request, resp *ghttp.Response, params map[string]any) ghttp.ErrorResponse {
	resp.JsonResponse(map[string]string{"feature": "newly added"})

	return nil
}

func main() {
	prev := ghttp.SetSkipHandlerRegister(true)
	defer ghttp.SetSkipHandlerRegister(prev)

	route := ghttp.NewSimpleRoute()
	route.SetEndpoint("/hello", &HelloHandler{})
	route.SetEndpoint("/new-feature", &NewHandler{})

	candidates := goai.Walk(route)
	doc := goai.Build(candidates, nil, goai.BuildOptions{
		Title:   "Merge Example API",
		Version: "1.0.0",
	})

	generated, err := goai.EmitYAML(doc)
	if err != nil {
		fmt.Fprintln(os.Stderr, "emit failed:", err)
		os.Exit(1)
	}

	merged, err := goai.Merge3Way(generated, []byte(handTunedBaseline), nil)
	if err != nil {
		fmt.Fprintln(os.Stderr, "merge failed:", err)
		os.Exit(1)
	}

	if _, err := os.Stdout.Write(merged); err != nil {
		fmt.Fprintln(os.Stderr, "write failed:", err)
		os.Exit(1)
	}

	fmt.Fprintln(os.Stderr, "----")
	fmt.Fprintf(os.Stderr, "Hand-tuned bytes: %d\n", len(handTunedBaseline))
	fmt.Fprintf(os.Stderr, "Generated bytes:  %d\n", len(generated))
	fmt.Fprintf(os.Stderr, "Merged bytes:     %d\n", len(merged))
	fmt.Fprintln(os.Stderr,
		"Note: /hello kept its hand-tuned description; /new-feature appears as a new path.")
}
