package goai

import (
	"context"
	"encoding/json"
	"go/ast"
	"go/build"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"os/exec"
	importpath "path"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"time"

	"gopkg.in/yaml.v3"
)

const _GoAIPrefix = "@goai."

// OperationEndpoint is the optional endpoint declaration parsed from
// `@goai.endpoint METHOD /path`. It documents which HTTP operation the
// comment describes; the route walker remains authoritative.
type OperationEndpoint struct {
	Method string
	Path   string
}

// OperationEndpointDoc is metadata scoped to a single declared endpoint.
type OperationEndpointDoc struct {
	Endpoint       OperationEndpoint
	Operation      Operation
	Schemas        map[string]*Schema
	SchemaPackages map[string]string
}

// OperationDoc is the doc-comment metadata for one handler method.
type OperationDoc struct {
	Endpoint           OperationEndpoint
	Endpoints          []OperationEndpoint
	EndpointOperations []OperationEndpointDoc
	Operation          Operation
	Schemas            map[string]*Schema
	SchemaPackages     map[string]string
}

// OperationDocExtractor returns OpenAPI operation metadata extracted from
// a handler method's source-code doc comment. The default implementation
// only reads namespaced `@goai.*` directives, keeping surrounding Go
// comments private to source readers.
type OperationDocExtractor func(handler any, methodName string) (*OperationDoc, bool)

// DefaultOperationDocExtractor returns the built-in extractor that locates
// each method's source file via runtime.FuncForPC, parses it with go/ast,
// and pulls the doc comment off the matching FuncDecl. Parsed files are
// cached, so repeat lookups are cheap.
//
// Parse strategy:
//   - The file path is derived from runtime.FuncForPC; when the binary was
//     built from a different module path or the source is not on disk
//     (e.g. embedded compilation), the extractor returns no operation.
//   - Only `@goai.*` directives are public OpenAPI input. Text before,
//     between, or after directives is considered source-only documentation.
//   - Complex OpenAPI objects can be supplied as compact JSON values on
//     namespaced directives such as `@goai.callback` and `schema=...`.
//
// The returned extractor is safe for concurrent use.
func DefaultOperationDocExtractor() OperationDocExtractor {
	return DefaultOperationDocExtractorWithBuildTags()
}

// DefaultOperationDocExtractorWithBuildTags returns the built-in docstring
// extractor using the supplied build tags when scanning sibling files for
// handler type docs and schema structs. Use this when the goai generator is
// compiled with custom build tags and schema/helper types live behind the same
// tags in separate files.
func DefaultOperationDocExtractorWithBuildTags(tags ...string) OperationDocExtractor {
	cache := &_DocstringCache{
		fset:      token.NewFileSet(),
		files:     map[string]*ast.File{},
		packages:  map[string][]*ast.File{},
		buildTags: _MergeBuildTags(_BuildTagsFromGOFLAGS(), tags),
	}

	return cache._ExtractOperationDoc
}

// _DocstringCache memoises parsed source files keyed by absolute path so
// repeated lookups for handlers in the same package don't re-parse.
type _DocstringCache struct {
	mu           sync.Mutex
	fset         *token.FileSet
	files        map[string]*ast.File
	packages     map[string][]*ast.File
	packageNames sync.Map
	buildTags    []string
}

type _DocParseContext struct {
	_SchemaBuilder *_ASTSchemaBuilder
}

type _ASTSchemaArg struct {
	_Expr    ast.Expr
	_Imports map[string]string
}

func (c *_DocstringCache) _ExtractOperationDoc(handler any, methodName string) (*OperationDoc, bool) {
	if handler == nil || methodName == "" {
		return nil, false
	}

	t := reflect.TypeOf(handler)
	if t == nil {
		return nil, false
	}

	method, ok := t.MethodByName(methodName)
	if !ok {
		return nil, false
	}

	ptr := method.Func.Pointer()
	if ptr == 0 {
		return nil, false
	}

	fn := runtime.FuncForPC(ptr)
	if fn == nil {
		return nil, false
	}

	file, _ := fn.FileLine(ptr)
	if file == "" || file == "<autogenerated>" {
		return nil, false
	}

	parsed := c._ParseFile(file)
	if parsed == nil {
		return nil, false
	}

	recvType := _ReceiverTypeName(t)
	if recvType == "" {
		return nil, false
	}

	files := c._ParsePackage(file, parsed.Name.Name)
	if len(files) == 0 {
		files = []*ast.File{parsed}
	}

	methodDoc := _FindMethodDoc([]*ast.File{parsed}, recvType, methodName)
	typeDoc := _FindTypeDoc(files, recvType)
	if methodDoc == "" && typeDoc == "" {
		return nil, false
	}

	combinedDoc := methodDoc
	if typeDoc != "" {
		combinedDoc = typeDoc + "\n" + methodDoc
	}

	ctx := &_DocParseContext{
		_SchemaBuilder: _NewASTSchemaBuilderWithPrimaryFileAndCache(files, _ReceiverPkgPath(t), filepath.Dir(file), c.buildTags, parsed, &c.packageNames),
	}

	var methodOnlyDoc *OperationDoc
	if methodDoc != "" {
		if parsedMethodDoc, ok := _ParseOpenAPIDocCommentWithContext(methodDoc, methodName, ctx); ok {
			methodOnlyDoc = parsedMethodDoc
		}
	}

	doc, ok := _ParseOpenAPIDocCommentWithContext(combinedDoc, methodName, ctx)
	if !ok {
		return nil, false
	}

	doc.Endpoint = OperationEndpoint{}
	doc.Endpoints = nil
	doc.EndpointOperations = nil
	if methodOnlyDoc != nil {
		doc.Endpoint = methodOnlyDoc.Endpoint
		doc.Endpoints = append([]OperationEndpoint(nil), methodOnlyDoc.Endpoints...)
		doc.EndpointOperations = append([]OperationEndpointDoc(nil), methodOnlyDoc.EndpointOperations...)
	}

	if methodOnlyDoc != nil && len(methodOnlyDoc.Operation.Tags) > 0 {
		doc.Operation.Tags = methodOnlyDoc.Operation.Tags
	}
	doc.Operation.Tags = _DeduplicateStrings(doc.Operation.Tags)

	return doc, true
}

func (c *_DocstringCache) _ParseFile(path string) *ast.File {
	c.mu.Lock()
	defer c.mu.Unlock()

	if f, ok := c.files[path]; ok {
		return f
	}

	parsed, err := parser.ParseFile(c.fset, path, nil, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		// Cache the failure as nil so we don't retry on every method
		// of the same handler. Parse errors are usually environmental
		// (file moved, binary stripped) and won't recover within a
		// single CLI run.
		c.files[path] = nil

		return nil
	}

	c.files[path] = parsed

	return parsed
}

func (c *_DocstringCache) _ParsePackage(path string, packageName string) []*ast.File {
	c.mu.Lock()
	defer c.mu.Unlock()

	dir := filepath.Dir(path)
	key := dir + "\x00" + packageName
	if files, ok := c.packages[key]; ok {
		return files
	}

	currentFile := filepath.Base(path)
	buildCtx := build.Default
	buildCtx.BuildTags = append(append([]string(nil), buildCtx.BuildTags...), c.buildTags...)
	filter := func(info fs.FileInfo) bool {
		if info.Name() == currentFile {
			return true
		}

		match, err := buildCtx.MatchFile(dir, info.Name())

		return err == nil && match
	}

	pkgs, err := parser.ParseDir(c.fset, dir, filter, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		c.packages[key] = nil

		return nil
	}

	pkg := pkgs[packageName]
	if pkg == nil {
		c.packages[key] = nil

		return nil
	}

	files := make([]*ast.File, 0, len(pkg.Files))
	for _, file := range pkg.Files {
		files = append(files, file)
	}

	c.packages[key] = files

	return files
}

// _ReceiverTypeName returns the unqualified, non-generic receiver type name to
// look for in the parsed file. Pointer receivers are unwrapped and generic
// type parameters stripped — `*CRUD[User]` yields "CRUD".
func _ReceiverTypeName(t reflect.Type) string {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}

	name := t.Name()
	// reflect returns names like "CRUD[User]" for instantiated generics.
	// Strip everything from '[' onward so we compare against the base name.
	if idx := strings.IndexByte(name, '['); idx >= 0 {
		name = name[:idx]
	}

	return name
}

func _ReceiverPkgPath(t reflect.Type) string {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}

	return t.PkgPath()
}

// _FindMethodDoc locates the FuncDecl whose receiver type matches recvType
// and whose Name matches methodName, returning the raw doc comment text.
// Returns "" when no match is found.
func _FindMethodDoc(files []*ast.File, recvType, methodName string) string {
	for _, file := range files {
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}

			if fn.Name == nil || fn.Name.Name != methodName {
				continue
			}

			if !_ReceiverMatches(fn.Recv, recvType) {
				continue
			}

			if fn.Doc == nil {
				return ""
			}

			return fn.Doc.Text()
		}
	}

	return ""
}

func _FindTypeDoc(files []*ast.File, typeName string) string {
	for _, file := range files {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}

			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || typeSpec.Name == nil || typeSpec.Name.Name != typeName {
					continue
				}

				if typeSpec.Doc != nil {
					return typeSpec.Doc.Text()
				}

				if gen.Doc != nil {
					return gen.Doc.Text()
				}

				return ""
			}
		}
	}

	return ""
}

// _ReceiverMatches reports whether the FuncDecl's receiver list names
// recvType (matching by unqualified type name; pointer receivers
// unwrapped). Returns false on package-level functions (no receiver).
func _ReceiverMatches(recv *ast.FieldList, recvType string) bool {
	if recv == nil || len(recv.List) == 0 {
		return false
	}

	expr := recv.List[0].Type
	if star, ok := expr.(*ast.StarExpr); ok {
		expr = star.X
	}

	ident, ok := expr.(*ast.Ident)
	if !ok {
		// Generic receiver: CRUD[T] or CRUD[T, U] is represented as
		// *ast.IndexExpr / *ast.IndexListExpr; unwrap to the base Ident.
		switch ix := expr.(type) {
		case *ast.IndexExpr:
			ident, ok = ix.X.(*ast.Ident)
		case *ast.IndexListExpr:
			ident, ok = ix.X.(*ast.Ident)
		}
		if !ok {
			return false
		}
	}

	return ident.Name == recvType
}

// _ParseOpenAPIDocComment extracts an OperationDoc from namespaced goai
// directives. Unmarked prose is ignored.
func _ParseOpenAPIDocComment(text, methodName string) (*OperationDoc, bool) {
	return _ParseOpenAPIDocCommentWithContext(text, methodName, nil)
}

func _ParseOpenAPIDocCommentWithContext(text, methodName string, ctx *_DocParseContext) (*OperationDoc, bool) {
	_ = methodName
	doc := &OperationDoc{}
	seen := false

	for _, line := range strings.Split(strings.TrimRight(text, "\n"), "\n") {
		name, payload, ok := _Directive(line)
		if !ok {
			continue
		}

		if _ApplyDirective(doc, ctx, name, payload) {
			seen = true
		}
	}

	if !seen {
		return nil, false
	}

	return doc, true
}

func _Directive(line string) (string, string, bool) {
	line = strings.TrimSpace(line)
	if !strings.HasPrefix(line, _GoAIPrefix) {
		return "", "", false
	}

	line = strings.TrimSpace(line[len(_GoAIPrefix):])
	if line == "" {
		return "", "", false
	}

	name, payload := _TakeFirstField(line)
	if name == "" {
		return "", "", false
	}

	return name, payload, true
}

func _ApplyDirective(doc *OperationDoc, ctx *_DocParseContext, name, payload string) bool {
	if indexedName, index, ok := _IndexedDirectiveName(name); ok {
		return _ApplyEndpointIndexedDirective(doc, ctx, indexedName, index, payload)
	}

	if target, ok := strings.CutPrefix(name, "endpoint."); ok {
		return _ApplyEndpointScopedDirective(doc, ctx, target, payload)
	}

	if target, ok := strings.CutSuffix(name, ".description"); ok {
		return _ApplyTargetDescription(doc, target, payload)
	}

	switch name {
	case "endpoint":
		return _ApplyEndpoint(doc, payload)
	case "summary":
		doc.Operation.Summary = strings.TrimSpace(payload)
	case "description":
		_AppendDescription(&doc.Operation.Description, strings.TrimSpace(payload))
	case "operationId":
		doc.Operation.OperationID = strings.TrimSpace(payload)
	case "tag":
		doc.Operation.Tags = append(doc.Operation.Tags, _SplitTagPayload(payload)...)
	case "deprecated":
		doc.Operation.Deprecated = true
	case "param":
		return _ApplyParameter(doc, ctx, payload)
	case "requestBody":
		return _ApplyRequestBody(doc, ctx, payload)
	case "response":
		return _ApplyResponse(doc, ctx, payload)
	case "header":
		return _ApplyHeader(doc, ctx, payload)
	case "link":
		return _ApplyLink(doc, payload)
	case "example":
		return _ApplyExample(doc, payload)
	case "security":
		return _ApplySecurity(doc, payload)
	case "server":
		return _ApplyServer(doc, payload)
	case "externalDocs":
		return _ApplyExternalDocs(doc, payload)
	case "callback":
		return _ApplyCallback(doc, payload)
	case "extension":
		return _ApplyExtension(&doc.Operation.Extensions, payload)
	default:
		return false
	}

	return true
}

func _IndexedDirectiveName(name string) (string, int, bool) {
	if !strings.HasSuffix(name, "]") {
		return "", 0, false
	}

	open := strings.LastIndex(name, "[")
	if open <= 0 || open == len(name)-2 {
		return "", 0, false
	}

	index, err := strconv.Atoi(name[open+1 : len(name)-1])
	if err != nil || index < 0 {
		return "", 0, false
	}

	return name[:open], index, true
}

func _ApplyTargetDescription(doc *OperationDoc, target string, payload string) bool {
	fields := _SplitDirectiveFields(payload)

	switch target {
	case "operation":
		_AppendDescription(&doc.Operation.Description, _DescriptionLine(fields, 0))
	case "param":
		if len(fields) < 3 {
			return false
		}

		param := _EnsureOperationParameter(&doc.Operation, fields[0], fields[1])
		_AppendDescription(&param.Description, _DescriptionLine(fields, 2))
	case "requestBody":
		if doc.Operation.RequestBody == nil {
			doc.Operation.RequestBody = &RequestBody{}
		}

		_AppendDescription(&doc.Operation.RequestBody.Description, _DescriptionLine(fields, 0))
	case "response":
		if len(fields) < 2 {
			return false
		}

		resp := _EnsureResponse(&doc.Operation, fields[0])
		_AppendDescription(&resp.Description, _DescriptionLine(fields, 1))
	case "header":
		if len(fields) < 3 {
			return false
		}

		resp := _EnsureResponse(&doc.Operation, fields[0])
		header := _EnsureHeader(resp, fields[1])
		_AppendDescription(&header.Description, _DescriptionLine(fields, 2))
	case "link":
		if len(fields) < 3 {
			return false
		}

		resp := _EnsureResponse(&doc.Operation, fields[0])
		link := _EnsureLink(resp, fields[1])
		_AppendDescription(&link.Description, _DescriptionLine(fields, 2))
	case "example":
		return _ApplyExampleDescription(doc, fields)
	case "server":
		if len(fields) < 2 {
			return false
		}

		server := _EnsureServer(&doc.Operation, fields[0])
		_AppendDescription(&server.Description, _DescriptionLine(fields, 1))
	case "externalDocs":
		if doc.Operation.ExternalDocs == nil {
			doc.Operation.ExternalDocs = &ExternalDocumentation{}
		}

		_AppendDescription(&doc.Operation.ExternalDocs.Description, _DescriptionLine(fields, 0))
	default:
		return false
	}

	return true
}

func _ApplyEndpoint(doc *OperationDoc, payload string) bool {
	fields := _SplitDirectiveFields(payload)
	if len(fields) < 2 {
		return false
	}

	endpoint := OperationEndpoint{
		Method: strings.ToUpper(fields[0]),
		Path:   fields[1],
	}
	_AppendOperationEndpoint(doc, endpoint, true)

	return true
}

func _ApplyEndpointScopedDirective(doc *OperationDoc, ctx *_DocParseContext, name string, payload string) bool {
	if name == "endpoint" || strings.HasPrefix(name, "endpoint.") {
		return false
	}

	method, rest := _TakeFirstField(payload)
	if method == "" {
		return false
	}

	path, rest := _TakeFirstField(rest)
	if path == "" {
		return false
	}

	endpoint := OperationEndpoint{
		Method: strings.ToUpper(method),
		Path:   path,
	}

	return _ApplyEndpointScopedOperation(doc, ctx, endpoint, name, rest)
}

func _ApplyEndpointIndexedDirective(doc *OperationDoc, ctx *_DocParseContext, name string, index int, payload string) bool {
	if name == "endpoint" || strings.HasPrefix(name, "endpoint.") {
		return false
	}

	endpoint, ok := _OperationEndpointAt(doc, index)
	if !ok {
		return false
	}

	return _ApplyEndpointScopedOperation(doc, ctx, endpoint, name, payload)
}

func _ApplyEndpointScopedOperation(doc *OperationDoc, ctx *_DocParseContext, endpoint OperationEndpoint, name string, payload string) bool {
	var base OperationEndpointDoc
	if endpointDoc := _FindEndpointOperationDoc(doc, endpoint); endpointDoc != nil {
		base = *endpointDoc
	}

	scoped := &OperationDoc{
		Operation:      _CloneOperation(base.Operation),
		Schemas:        _CloneSchemaMap(base.Schemas),
		SchemaPackages: _CloneSchemaPackageMap(base.SchemaPackages),
	}
	if !_ApplyDirective(scoped, ctx, name, payload) {
		return false
	}

	endpointDoc := _EndpointOperationDoc(doc, endpoint)
	if endpointDoc == nil {
		return false
	}

	endpointDoc.Operation = scoped.Operation
	endpointDoc.Schemas = scoped.Schemas
	endpointDoc.SchemaPackages = scoped.SchemaPackages

	return true
}

func _OperationEndpointAt(doc *OperationDoc, index int) (OperationEndpoint, bool) {
	if doc == nil || index < 0 {
		return OperationEndpoint{}, false
	}

	if len(doc.Endpoints) > 0 {
		if index >= len(doc.Endpoints) {
			return OperationEndpoint{}, false
		}

		return doc.Endpoints[index], true
	}

	if index == 0 && doc.Endpoint.Method != "" && doc.Endpoint.Path != "" {
		return doc.Endpoint, true
	}

	return OperationEndpoint{}, false
}

func _EndpointOperationDoc(doc *OperationDoc, endpoint OperationEndpoint) *OperationEndpointDoc {
	if doc == nil || endpoint.Method == "" || endpoint.Path == "" {
		return nil
	}

	for i := range doc.EndpointOperations {
		if _OperationEndpointEqual(doc.EndpointOperations[i].Endpoint, endpoint) {
			return &doc.EndpointOperations[i]
		}
	}

	doc.EndpointOperations = append(doc.EndpointOperations, OperationEndpointDoc{Endpoint: endpoint})
	return &doc.EndpointOperations[len(doc.EndpointOperations)-1]
}

func _FindEndpointOperationDoc(doc *OperationDoc, endpoint OperationEndpoint) *OperationEndpointDoc {
	if doc == nil || endpoint.Method == "" || endpoint.Path == "" {
		return nil
	}

	for i := range doc.EndpointOperations {
		if _OperationEndpointEqual(doc.EndpointOperations[i].Endpoint, endpoint) {
			return &doc.EndpointOperations[i]
		}
	}

	return nil
}

func _AppendOperationEndpoint(doc *OperationDoc, endpoint OperationEndpoint, updateAlias bool) {
	if doc == nil || endpoint.Method == "" || endpoint.Path == "" {
		return
	}

	if updateAlias {
		doc.Endpoint = endpoint
	}

	for _, existing := range doc.Endpoints {
		if _OperationEndpointEqual(existing, endpoint) {
			return
		}
	}

	doc.Endpoints = append(doc.Endpoints, endpoint)
}

func _OperationEndpointEqual(a OperationEndpoint, b OperationEndpoint) bool {
	return strings.EqualFold(a.Method, b.Method) && a.Path == b.Path
}

func _ApplyParameter(doc *OperationDoc, ctx *_DocParseContext, payload string) bool {
	fields := _SplitDirectiveFields(payload)
	if len(fields) < 5 {
		return false
	}

	description, optionFields := _DescriptionAndOptions(fields, 4)
	opts := _OptionMap(optionFields)
	param := &Parameter{
		In:          fields[0],
		Name:        fields[1],
		Description: description,
		Required:    _RequiredToken(fields[3]) || fields[0] == "path",
		Schema:      _SchemaFromDoc(doc, ctx, fields[2], opts),
	}

	_ApplyParameterOptions(param, opts)
	existing := _FindOperationParameter(doc.Operation.Parameters, param.In, param.Name)
	if existing == nil {
		doc.Operation.Parameters = append(doc.Operation.Parameters, param)
	} else {
		_MergeParameterWithinDoc(existing, param)
	}

	return true
}

func _MergeParameterWithinDoc(dst *Parameter, src *Parameter) {
	_AppendDescriptionOnce(&dst.Description, src.Description)
	_MergeParameterFallback(dst, src)

	if !dst.Required {
		dst.Required = src.Required
	}

	if !dst.Deprecated {
		dst.Deprecated = src.Deprecated
	}

	if !dst.AllowEmptyValue {
		dst.AllowEmptyValue = src.AllowEmptyValue
	}

	if !dst.AllowReserved {
		dst.AllowReserved = src.AllowReserved
	}
}

func _ApplyRequestBody(doc *OperationDoc, ctx *_DocParseContext, payload string) bool {
	fields := _SplitDirectiveFields(payload)
	if len(fields) < 4 {
		return false
	}

	description, optionFields := _DescriptionAndOptions(fields, 3)
	opts := _OptionMap(optionFields)
	mediaType := fields[1]
	mt := &MediaType{Schema: _SchemaFromDoc(doc, ctx, fields[2], opts)}
	if raw, ok := opts["example"]; ok {
		mt.Example = _ParseValue(raw)
	}

	docBody := &RequestBody{
		Description: description,
		Required:    _RequiredToken(fields[0]),
		Content:     map[string]*MediaType{mediaType: mt},
	}
	_ApplyExtensions(&docBody.Extensions, opts)

	if doc.Operation.RequestBody == nil {
		doc.Operation.RequestBody = docBody
	} else {
		_AppendDescriptionOnce(&doc.Operation.RequestBody.Description, docBody.Description)

		if !doc.Operation.RequestBody.Required {
			doc.Operation.RequestBody.Required = docBody.Required
		}

		if len(doc.Operation.RequestBody.Content) == 0 {
			doc.Operation.RequestBody.Content = docBody.Content
		} else {
			_MergeMediaTypesFallback(doc.Operation.RequestBody.Content, docBody.Content)
		}
		_ApplyExtensions(&doc.Operation.RequestBody.Extensions, opts)
	}

	return true
}

func _ApplyResponse(doc *OperationDoc, ctx *_DocParseContext, payload string) bool {
	fields := _SplitDirectiveFields(payload)
	if len(fields) < 2 {
		return false
	}

	description, optionFields := _DescriptionAndOptions(fields, 1)
	opts := _OptionMap(optionFields)
	resp := _EnsureResponse(&doc.Operation, fields[0])
	_AppendDescriptionOnce(&resp.Description, description)
	_ApplyExtensions(&resp.Extensions, opts)

	mediaType := opts["mediaType"]
	if mediaType == "" {
		mediaType = opts["contentType"]
	}

	typeToken := opts["type"]
	if typeToken == "" {
		typeToken = opts["schemaType"]
	}
	if typeToken == "" {
		typeToken = opts["goType"]
	}

	if mediaType != "" || typeToken != "" || opts["schema"] != "" || opts["example"] != "" {
		if mediaType == "" {
			mediaType = "application/json"
		}

		if resp.Content == nil {
			resp.Content = map[string]*MediaType{}
		}

		mt := resp.Content[mediaType]
		if mt == nil {
			mt = &MediaType{}
			resp.Content[mediaType] = mt
		}

		if typeToken != "" || opts["schema"] != "" {
			mt.Schema = _SchemaFromDoc(doc, ctx, typeToken, opts)
		}

		if raw, ok := opts["example"]; ok {
			mt.Example = _ParseValue(raw)
		}
	}

	return true
}

func _ApplyHeader(doc *OperationDoc, ctx *_DocParseContext, payload string) bool {
	fields := _SplitDirectiveFields(payload)
	if len(fields) < 4 {
		return false
	}

	description, optionFields := _DescriptionAndOptions(fields, 3)
	opts := _OptionMap(optionFields)
	resp := _EnsureResponse(&doc.Operation, fields[0])
	if resp.Headers == nil {
		resp.Headers = map[string]*Header{}
	}

	header := &Header{
		Description: description,
		Required:    _BoolOption(opts, "required") || _Contains(optionFields, "required"),
		Schema:      _SchemaFromDoc(doc, ctx, fields[2], opts),
	}
	_ApplyHeaderOptions(header, opts)
	if existing := resp.Headers[fields[1]]; existing != nil {
		_MergeHeaderWithinDoc(existing, header)
	} else {
		resp.Headers[fields[1]] = header
	}

	return true
}

func _MergeHeaderWithinDoc(dst *Header, src *Header) {
	_AppendDescriptionOnce(&dst.Description, src.Description)
	_MergeHeaderFallback(dst, src)

	if !dst.Required {
		dst.Required = src.Required
	}

	if !dst.Deprecated {
		dst.Deprecated = src.Deprecated
	}

	if !dst.AllowEmptyValue {
		dst.AllowEmptyValue = src.AllowEmptyValue
	}

	if !dst.AllowReserved {
		dst.AllowReserved = src.AllowReserved
	}
}

func _ApplyHeaderOptions(header *Header, opts map[string]string) {
	if raw, ok := opts["example"]; ok {
		header.Example = _ParseValue(raw)
	}

	if raw, ok := opts["examples"]; ok {
		examples := map[string]*Example{}
		if _DecodeStructured(raw, &examples) {
			header.Examples = examples
		}
	}

	if raw, ok := opts["style"]; ok {
		header.Style = raw
	}

	if raw, ok := opts["explode"]; ok {
		v := _ParseBool(raw)
		header.Explode = &v
	}

	if mediaType := opts["content"]; mediaType != "" {
		header.Content = map[string]*MediaType{
			mediaType: {Schema: header.Schema},
		}
		header.Schema = nil
	}

	header.Deprecated = _BoolOption(opts, "deprecated")
	header.AllowEmptyValue = _BoolOption(opts, "allowEmptyValue")
	header.AllowReserved = _BoolOption(opts, "allowReserved")

	_ApplyExtensions(&header.Extensions, opts)
}

func _ApplyLink(doc *OperationDoc, payload string) bool {
	fields := _SplitDirectiveFields(payload)
	if len(fields) < 3 {
		return false
	}

	description, optionFields := _DescriptionAndOptions(fields, 3)
	opts := _OptionMap(optionFields)
	resp := _EnsureResponse(&doc.Operation, fields[0])
	if resp.Links == nil {
		resp.Links = map[string]*Link{}
	}

	link := &Link{Description: description}
	if operationID := opts["operationId"]; operationID != "" {
		link.OperationID = operationID
	} else if operationRef := opts["operationRef"]; operationRef != "" {
		link.OperationRef = operationRef
	} else if strings.HasPrefix(fields[2], "#/") || strings.HasPrefix(fields[2], "http://") || strings.HasPrefix(fields[2], "https://") {
		link.OperationRef = fields[2]
	} else if fields[2] != "-" {
		link.OperationID = fields[2]
	}

	_ApplyLinkOptions(link, opts)
	if existing := resp.Links[fields[1]]; existing != nil {
		_MergeLinkWithinDoc(existing, link)
	} else {
		resp.Links[fields[1]] = link
	}

	return true
}

func _MergeLinkWithinDoc(dst *Link, src *Link) {
	_AppendDescriptionOnce(&dst.Description, src.Description)

	if dst.OperationRef == "" {
		dst.OperationRef = src.OperationRef
	}

	if dst.OperationID == "" {
		dst.OperationID = src.OperationID
	}

	if len(dst.Parameters) == 0 && len(src.Parameters) > 0 {
		dst.Parameters = src.Parameters
	}

	if dst.RequestBody == nil {
		dst.RequestBody = src.RequestBody
	}

	if dst.Server == nil {
		dst.Server = src.Server
	}

	if len(src.Extensions) > 0 {
		if dst.Extensions == nil {
			dst.Extensions = map[string]any{}
		}

		for key, value := range src.Extensions {
			if _, exists := dst.Extensions[key]; !exists {
				dst.Extensions[key] = value
			}
		}
	}
}

func _ApplyLinkOptions(link *Link, opts map[string]string) {
	if raw := opts["parameters"]; raw != "" {
		params := map[string]any{}
		if _DecodeStructured(raw, &params) {
			link.Parameters = params
		}
	}

	if raw := opts["requestBody"]; raw != "" {
		link.RequestBody = _ParseValue(raw)
	}

	if raw := opts["server"]; raw != "" {
		var server Server
		if _DecodeStructured(raw, &server) {
			link.Server = &server
		}
	}

	_ApplyExtensions(&link.Extensions, opts)
}

func _ApplyExample(doc *OperationDoc, payload string) bool {
	fields := _SplitDirectiveFields(payload)
	if len(fields) < 2 {
		return false
	}

	switch fields[0] {
	case "param":
		if len(fields) < 4 {
			return false
		}

		param := _EnsureOperationParameter(&doc.Operation, fields[1], fields[2])

		if param.Examples == nil {
			param.Examples = map[string]*Example{}
		}

		ex, ok := _ExampleFromFields(fields, 4)
		if !ok {
			return false
		}

		_MergeExampleMapEntry(param.Examples, fields[3], ex)
	case "request":
		if len(fields) < 3 {
			return false
		}

		if doc.Operation.RequestBody == nil {
			doc.Operation.RequestBody = &RequestBody{}
		}

		mt := _EnsureRequestMediaType(doc.Operation.RequestBody, fields[1])
		if mt.Examples == nil {
			mt.Examples = map[string]*Example{}
		}

		ex, ok := _ExampleFromFields(fields, 3)
		if !ok {
			return false
		}

		_MergeExampleMapEntry(mt.Examples, fields[2], ex)
	case "response":
		if len(fields) < 4 {
			return false
		}

		resp := _EnsureResponse(&doc.Operation, fields[1])
		mt := _EnsureResponseMediaType(resp, fields[2])
		if mt.Examples == nil {
			mt.Examples = map[string]*Example{}
		}

		ex, ok := _ExampleFromFields(fields, 4)
		if !ok {
			return false
		}

		_MergeExampleMapEntry(mt.Examples, fields[3], ex)
	default:
		return false
	}

	return true
}

func _ApplySecurity(doc *OperationDoc, payload string) bool {
	fields := _SplitDirectiveFields(payload)
	if len(fields) == 0 {
		return false
	}

	if fields[0] == "none" || fields[0] == "[]" {
		empty := []map[string][]string{}
		doc.Operation.Security = &empty

		return true
	}

	sec := []map[string][]string{}
	if doc.Operation.Security != nil {
		sec = append(sec, (*doc.Operation.Security)...)
	}

	sec = append(sec, map[string][]string{fields[0]: append([]string(nil), fields[1:]...)})
	doc.Operation.Security = &sec

	return true
}

func _ApplyServer(doc *OperationDoc, payload string) bool {
	fields := _SplitDirectiveFields(payload)
	if len(fields) == 0 {
		return false
	}

	description, _ := _DescriptionAndOptions(fields, 1)
	server := _EnsureServer(&doc.Operation, fields[0])
	_AppendDescriptionOnce(&server.Description, description)

	return true
}

func _ApplyExternalDocs(doc *OperationDoc, payload string) bool {
	fields := _SplitDirectiveFields(payload)
	if len(fields) == 0 {
		return false
	}

	description, _ := _DescriptionAndOptions(fields, 1)
	if doc.Operation.ExternalDocs == nil {
		doc.Operation.ExternalDocs = &ExternalDocumentation{}
	}

	doc.Operation.ExternalDocs.URL = fields[0]
	_AppendDescriptionOnce(&doc.Operation.ExternalDocs.Description, description)

	return true
}

func _ApplyCallback(doc *OperationDoc, payload string) bool {
	name, raw := _TakeFirstField(payload)
	if name == "" || raw == "" {
		return false
	}

	var callback Callback
	if !_DecodeStructured(raw, &callback) {
		return false
	}

	if doc.Operation.Callbacks == nil {
		doc.Operation.Callbacks = map[string]Callback{}
	}

	doc.Operation.Callbacks[name] = callback

	return true
}

func _ApplyExtension(extensions *map[string]any, payload string) bool {
	key, raw := _TakeFirstField(payload)
	if key == "" || !strings.HasPrefix(key, "x-") {
		return false
	}

	if *extensions == nil {
		*extensions = map[string]any{}
	}

	(*extensions)[key] = _ParseValue(raw)

	return true
}

func _ExampleFromFields(fields []string, start int) (*Example, bool) {
	if len(fields) <= start {
		return nil, false
	}

	opts := _OptionMap(fields[start:])
	if raw := opts["example"]; raw != "" {
		var ex Example
		if _DecodeStructured(raw, &ex) {
			return &ex, true
		}

		return &Example{Value: _ParseValue(raw)}, true
	}

	if len(fields) <= start+1 {
		return nil, false
	}

	ex := &Example{
		Summary: fields[start],
		Value:   _ParseValue(fields[start+1]),
	}
	_ApplyExampleOptions(ex, _OptionMap(fields[start+2:]))

	return ex, true
}

func _ApplyExampleDescription(doc *OperationDoc, fields []string) bool {
	if len(fields) == 0 {
		return false
	}

	var ex *Example
	switch fields[0] {
	case "param":
		if len(fields) < 5 {
			return false
		}

		param := _EnsureOperationParameter(&doc.Operation, fields[1], fields[2])
		if param.Examples == nil {
			param.Examples = map[string]*Example{}
		}

		ex = _EnsureExample(param.Examples, fields[3])
		_AppendDescription(&ex.Description, _DescriptionLine(fields, 4))
	case "request":
		if len(fields) < 4 {
			return false
		}

		if doc.Operation.RequestBody == nil {
			doc.Operation.RequestBody = &RequestBody{}
		}

		mt := _EnsureRequestMediaType(doc.Operation.RequestBody, fields[1])
		if mt.Examples == nil {
			mt.Examples = map[string]*Example{}
		}

		ex = _EnsureExample(mt.Examples, fields[2])
		_AppendDescription(&ex.Description, _DescriptionLine(fields, 3))
	case "response":
		if len(fields) < 5 {
			return false
		}

		resp := _EnsureResponse(&doc.Operation, fields[1])
		mt := _EnsureResponseMediaType(resp, fields[2])
		if mt.Examples == nil {
			mt.Examples = map[string]*Example{}
		}

		ex = _EnsureExample(mt.Examples, fields[3])
		_AppendDescription(&ex.Description, _DescriptionLine(fields, 4))
	default:
		return false
	}

	return ex != nil
}

func _EnsureExample(examples map[string]*Example, name string) *Example {
	ex := examples[name]
	if ex == nil {
		ex = &Example{}
		examples[name] = ex
	}

	return ex
}

func _MergeExampleMapEntry(examples map[string]*Example, name string, src *Example) {
	existing := examples[name]
	if existing == nil {
		examples[name] = src

		return
	}

	_MergeExampleWithinDoc(existing, src)
}

func _MergeExampleWithinDoc(dst *Example, src *Example) {
	if dst.Summary == "" {
		dst.Summary = src.Summary
	}

	_AppendDescriptionOnce(&dst.Description, src.Description)

	if dst.Value == nil {
		dst.Value = src.Value
	}

	if dst.ExternalValue == "" {
		dst.ExternalValue = src.ExternalValue
	}

	if len(src.Extensions) > 0 {
		if dst.Extensions == nil {
			dst.Extensions = map[string]any{}
		}

		for key, value := range src.Extensions {
			if _, exists := dst.Extensions[key]; !exists {
				dst.Extensions[key] = value
			}
		}
	}
}

func _ApplyExampleOptions(ex *Example, opts map[string]string) {
	if raw := opts["summary"]; raw != "" {
		ex.Summary = raw
	}

	if raw := opts["description"]; raw != "" {
		ex.Description = raw
	}

	if raw := opts["externalValue"]; raw != "" {
		ex.ExternalValue = raw
	}

	_ApplyExtensions(&ex.Extensions, opts)
}

func _ApplyParameterOptions(param *Parameter, opts map[string]string) {
	if raw, ok := opts["example"]; ok {
		param.Example = _ParseValue(raw)
	}

	if raw, ok := opts["style"]; ok {
		param.Style = raw
	}

	if raw, ok := opts["explode"]; ok {
		v := _ParseBool(raw)
		param.Explode = &v
	}

	param.Deprecated = _BoolOption(opts, "deprecated")
	param.AllowEmptyValue = _BoolOption(opts, "allowEmptyValue")
	param.AllowReserved = _BoolOption(opts, "allowReserved")

	if mediaType := opts["content"]; mediaType != "" {
		param.Content = map[string]*MediaType{
			mediaType: {Schema: param.Schema},
		}
		param.Schema = nil
	}

	_ApplyExtensions(&param.Extensions, opts)
}

func _ApplyExtensions(extensions *map[string]any, opts map[string]string) {
	for key, raw := range opts {
		if !strings.HasPrefix(key, "x-") {
			continue
		}

		if *extensions == nil {
			*extensions = map[string]any{}
		}

		(*extensions)[key] = _ParseValue(raw)
	}
}

func _AppendDescription(dst *string, line string) {
	if line == "" {
		return
	}

	if *dst == "" {
		*dst = line

		return
	}

	*dst += "\n" + line
}

func _AppendDescriptionOnce(dst *string, text string) {
	for _, line := range strings.Split(text, "\n") {
		if _DescriptionHasLine(*dst, line) {
			continue
		}

		_AppendDescription(dst, line)
	}
}

func _DescriptionHasLine(description string, line string) bool {
	if line == "" {
		return true
	}

	for _, existing := range strings.Split(description, "\n") {
		if existing == line {
			return true
		}
	}

	return false
}

func _DescriptionLine(fields []string, start int) string {
	if len(fields) <= start {
		return ""
	}

	return strings.Join(fields[start:], " ")
}

func _SplitTagPayload(payload string) []string {
	fields := _SplitDirectiveFields(strings.ReplaceAll(payload, ",", " "))
	out := make([]string, 0, len(fields))
	for _, f := range fields {
		if f != "" {
			out = append(out, f)
		}
	}

	return out
}

func _DescriptionAndOptions(fields []string, start int) (string, []string) {
	var desc []string
	i := start
	for ; i < len(fields); i++ {
		if _IsOptionField(fields[i]) {
			break
		}

		desc = append(desc, fields[i])
	}

	return strings.Join(desc, " "), fields[i:]
}

func _IsOptionField(field string) bool {
	if strings.Contains(field, "=") {
		return true
	}

	switch field {
	case "required", "optional", "deprecated", "allowEmptyValue", "allowReserved":
		return true
	default:
		return false
	}
}

func _OptionMap(fields []string) map[string]string {
	opts := map[string]string{}
	for _, field := range fields {
		key, value, ok := strings.Cut(field, "=")
		if !ok {
			opts[field] = "true"

			continue
		}

		opts[key] = value
	}

	return opts
}

func _SchemaFromDoc(doc *OperationDoc, ctx *_DocParseContext, typeToken string, opts map[string]string) *Schema {
	if opts["schema"] != "" {
		return _SchemaFrom(typeToken, opts)
	}

	if ctx != nil && ctx._SchemaBuilder != nil {
		goType := opts["goType"]
		if goType == "" {
			goType = opts["schemaType"]
		}

		if goType == "" {
			goType = typeToken
		}

		if schema, ok := ctx._SchemaBuilder._SchemaForTypeName(goType); ok {
			_MergeDocSchemas(doc, ctx._SchemaBuilder._Components)
			_MergeDocSchemaPackages(doc, ctx._SchemaBuilder._ComponentPkgs)
			_ApplySchemaOptions(schema, opts)

			return schema
		}
	}

	return _SchemaFrom(typeToken, opts)
}

func _MergeDocSchemas(doc *OperationDoc, schemas map[string]*Schema) {
	if len(schemas) == 0 {
		return
	}

	if doc.Schemas == nil {
		doc.Schemas = map[string]*Schema{}
	}

	for name, schema := range schemas {
		if _, exists := doc.Schemas[name]; !exists {
			doc.Schemas[name] = schema
		}
	}
}

func _MergeDocSchemaPackages(doc *OperationDoc, packages map[string]string) {
	if len(packages) == 0 {
		return
	}

	if doc.SchemaPackages == nil {
		doc.SchemaPackages = map[string]string{}
	}

	for name, pkg := range packages {
		if _, exists := doc.SchemaPackages[name]; !exists {
			doc.SchemaPackages[name] = pkg
		}
	}
}

func _SchemaFrom(typeToken string, opts map[string]string) *Schema {
	var schema *Schema
	if raw := opts["schema"]; raw != "" {
		var parsed Schema
		if _DecodeStructured(raw, &parsed) {
			schema = &parsed
		}
	}

	if schema == nil {
		schema = _SchemaFromType(typeToken)
	}

	if schema == nil {
		return nil
	}

	if schema.Type == "" && typeToken != "" && !strings.HasPrefix(typeToken, "#/") {
		schema.Type = typeToken
	}

	_ApplySchemaOptions(schema, opts)

	return schema
}

func _ApplySchemaOptions(schema *Schema, opts map[string]string) {
	if schema == nil {
		return
	}

	if raw := opts["format"]; raw != "" {
		schema.Format = raw
	}

	if raw := opts["default"]; raw != "" {
		schema.Default = _ParseValue(raw)
	}

	if raw := opts["enum"]; raw != "" {
		for _, item := range strings.Split(raw, ",") {
			schema.Enum = append(schema.Enum, _ParseValue(strings.TrimSpace(item)))
		}
	}

	if raw := opts["nullable"]; raw != "" {
		schema.Nullable = _ParseBool(raw)
	}
}

func _SchemaFromType(typeToken string) *Schema {
	switch {
	case typeToken == "":
		return nil
	case strings.HasPrefix(typeToken, "#/"):
		return &Schema{Ref: typeToken}
	case strings.HasPrefix(typeToken, "$ref:"):
		return &Schema{Ref: strings.TrimPrefix(typeToken, "$ref:")}
	case strings.HasPrefix(typeToken, "ref:"):
		return &Schema{Ref: strings.TrimPrefix(typeToken, "ref:")}
	case strings.HasPrefix(typeToken, "array:"):
		itemType := strings.TrimPrefix(typeToken, "array:")

		return &Schema{Type: "array", Items: _SchemaFromType(itemType)}
	default:
		return &Schema{Type: typeToken}
	}
}

type _ASTSchemaBuilder struct {
	_PkgPath         string
	_RootPkgPath     string
	_PackageName     string
	_Dir             string
	_BuildTags       []string
	_Imports         map[string]string
	_ImportNames     *sync.Map
	_SelfAliases     map[string]bool
	_ImportBuilders  map[string]*_ASTSchemaBuilder
	_TypeSpecs       map[string]*ast.TypeSpec
	_TypeSpecImports map[*ast.TypeSpec]map[string]string
	_TypeSpecNames   map[*ast.TypeSpec]string
	_Components      map[string]*Schema
	_ComponentPkgs   map[string]string
	_ComponentOwners map[string]string
	_Visiting        map[string]bool
}

func _NewASTSchemaBuilder(files []*ast.File, pkgPath string) *_ASTSchemaBuilder {
	return _NewASTSchemaBuilderWithPrimaryFile(files, pkgPath, "", nil, nil)
}

func _NewASTSchemaBuilderWithContext(files []*ast.File, pkgPath string, dir string, buildTags []string) *_ASTSchemaBuilder {
	return _NewASTSchemaBuilderWithPrimaryFile(files, pkgPath, dir, buildTags, nil)
}

func _NewASTSchemaBuilderWithPrimaryFile(files []*ast.File, pkgPath string, dir string, buildTags []string, primary *ast.File) *_ASTSchemaBuilder {
	return _NewASTSchemaBuilderWithPrimaryFileAndCache(files, pkgPath, dir, buildTags, primary, nil)
}

func _NewASTSchemaBuilderWithPrimaryFileAndCache(files []*ast.File, pkgPath string, dir string, buildTags []string, primary *ast.File, importNames *sync.Map) *_ASTSchemaBuilder {
	if importNames == nil {
		importNames = &sync.Map{}
	}

	return _NewASTSchemaBuilderWithState(
		files,
		pkgPath,
		pkgPath,
		dir,
		buildTags,
		_ASTImportsFromPrimary(files, primary, dir, buildTags, importNames),
		map[string]bool{},
		map[string]*Schema{},
		map[string]string{},
		map[string]string{},
		map[string]bool{},
		map[string]*_ASTSchemaBuilder{},
		importNames,
	)
}

func _NewASTSchemaBuilderWithState(
	files []*ast.File,
	pkgPath string,
	rootPkgPath string,
	dir string,
	buildTags []string,
	imports map[string]string,
	selfAliases map[string]bool,
	components map[string]*Schema,
	componentPkgs map[string]string,
	componentOwners map[string]string,
	visiting map[string]bool,
	importBuilders map[string]*_ASTSchemaBuilder,
	importNames *sync.Map,
) *_ASTSchemaBuilder {
	if importNames == nil {
		importNames = &sync.Map{}
	}

	b := &_ASTSchemaBuilder{
		_PkgPath:         pkgPath,
		_RootPkgPath:     rootPkgPath,
		_Dir:             dir,
		_BuildTags:       append([]string(nil), buildTags...),
		_Imports:         _CloneStringMap(imports),
		_ImportNames:     importNames,
		_SelfAliases:     _CloneBoolMap(selfAliases),
		_ImportBuilders:  importBuilders,
		_TypeSpecs:       map[string]*ast.TypeSpec{},
		_TypeSpecImports: map[*ast.TypeSpec]map[string]string{},
		_TypeSpecNames:   map[*ast.TypeSpec]string{},
		_Components:      components,
		_ComponentPkgs:   componentPkgs,
		_ComponentOwners: componentOwners,
		_Visiting:        visiting,
	}

	if pkgPath != "" {
		if _, exists := importBuilders[pkgPath]; !exists {
			importBuilders[pkgPath] = b
		}
	}

	for _, file := range files {
		if b._PackageName == "" && file.Name != nil {
			b._PackageName = file.Name.Name
		}

		fileImports := _ASTImports(file, b._Dir, b._BuildTags, b._ImportNames)

		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}

			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || typeSpec.Name == nil {
					continue
				}

				b._TypeSpecs[typeSpec.Name.Name] = typeSpec
				b._TypeSpecImports[typeSpec] = fileImports
				b._TypeSpecNames[typeSpec] = _ASTSchemaName(gen, typeSpec)
			}
		}
	}

	return b
}

func _ASTSchemaName(gen *ast.GenDecl, typeSpec *ast.TypeSpec) string {
	text := ""
	if typeSpec != nil && typeSpec.Doc != nil {
		text = typeSpec.Doc.Text()
	} else if gen != nil && gen.Doc != nil {
		text = gen.Doc.Text()
	}

	for _, line := range strings.Split(strings.TrimRight(text, "\n"), "\n") {
		name, payload, ok := _Directive(line)
		if !ok {
			continue
		}

		switch name {
		case "schemaName", "componentName":
			return _SanitizeComponentName(strings.TrimSpace(payload))
		}
	}

	return ""
}

func _ASTImportsFromPrimary(files []*ast.File, primary *ast.File, dir string, buildTags []string, importNames *sync.Map) map[string]string {
	out := map[string]string{}
	conflicts := map[string]bool{}
	for _, file := range files {
		for alias, importPath := range _ASTImports(file, dir, buildTags, importNames) {
			if existing, exists := out[alias]; exists && existing != importPath {
				delete(out, alias)
				conflicts[alias] = true

				continue
			}

			if !conflicts[alias] {
				out[alias] = importPath
			}
		}
	}

	if primary != nil {
		for alias, importPath := range _ASTImports(primary, dir, buildTags, importNames) {
			out[alias] = importPath
		}
	}

	return out
}

func _ASTImports(file *ast.File, dir string, buildTags []string, importNames *sync.Map) map[string]string {
	out := map[string]string{}
	if file == nil {
		return out
	}

	for _, spec := range file.Imports {
		alias, importPath, ok := _ASTImportBinding(spec, dir, buildTags, importNames)
		if ok {
			out[alias] = importPath
		}
	}

	return out
}

func _CloneStringMap(in map[string]string) map[string]string {
	out := map[string]string{}
	for key, value := range in {
		out[key] = value
	}

	return out
}

func _CloneBoolMap(in map[string]bool) map[string]bool {
	out := map[string]bool{}
	for key, value := range in {
		out[key] = value
	}

	return out
}

func _ASTImportBinding(spec *ast.ImportSpec, dir string, buildTags []string, importNames *sync.Map) (string, string, bool) {
	if spec == nil || spec.Path == nil {
		return "", "", false
	}

	importPath, err := strconv.Unquote(spec.Path.Value)
	if err != nil || importPath == "" {
		return "", "", false
	}

	if spec.Name != nil {
		switch spec.Name.Name {
		case ".", "_":
			return "", "", false
		case "":
			return _ImportPackageName(importPath, dir, buildTags, importNames), importPath, true
		default:
			return spec.Name.Name, importPath, true
		}
	}

	return _ImportPackageName(importPath, dir, buildTags, importNames), importPath, true
}

func (b *_ASTSchemaBuilder) _SchemaForTypeName(raw string) (*Schema, bool) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil, false
	}

	if strings.HasPrefix(raw, "[]") {
		item, ok := b._SchemaForTypeName(strings.TrimSpace(raw[2:]))
		if !ok {
			return nil, false
		}

		return &Schema{Type: "array", Items: item}, true
	}

	if itemType, ok := strings.CutPrefix(raw, "array:"); ok {
		item, ok := b._SchemaForTypeName(strings.TrimSpace(itemType))
		if !ok {
			return nil, false
		}

		return &Schema{Type: "array", Items: item}, true
	}

	if strings.HasPrefix(raw, "*") {
		inner, ok := b._SchemaForTypeName(strings.TrimSpace(raw[1:]))
		if !ok {
			return nil, false
		}

		return _NullableSchema(inner), true
	}

	expr, err := parser.ParseExpr(raw)
	if err == nil {
		return b._SchemaFromTopLevelExpr(expr, b._Imports)
	}

	typeSpec := b._TypeSpecs[raw]
	if typeSpec == nil {
		return nil, false
	}

	return b._SchemaFromTypeSpec(raw, typeSpec), true
}

func (b *_ASTSchemaBuilder) _SchemaFromTopLevelExpr(expr ast.Expr, imports map[string]string) (*Schema, bool) {
	switch t := expr.(type) {
	case *ast.Ident:
		typeSpec := b._TypeSpecs[t.Name]
		if typeSpec == nil {
			return nil, false
		}

		return b._SchemaFromTypeSpec(t.Name, typeSpec), true
	case *ast.SelectorExpr:
		return b._SchemaFromSelectorExpr(t, imports)
	case *ast.StarExpr:
		inner, ok := b._SchemaFromTopLevelExpr(t.X, imports)
		if !ok {
			return nil, false
		}

		return _NullableSchema(inner), true
	case *ast.ArrayType:
		item, ok := b._SchemaFromTopLevelExpr(t.Elt, imports)
		if !ok {
			return nil, false
		}

		return &Schema{Type: "array", Items: item}, true
	case *ast.IndexExpr:
		return b._SchemaFromGenericExpr(t.X, _SchemaArgs([]ast.Expr{t.Index}, imports), imports)
	case *ast.IndexListExpr:
		return b._SchemaFromGenericExpr(t.X, _SchemaArgs(t.Indices, imports), imports)
	default:
		return nil, false
	}
}

func (b *_ASTSchemaBuilder) _SchemaFromGenericExpr(base ast.Expr, args []_ASTSchemaArg, imports map[string]string) (*Schema, bool) {
	typeName, builder, ok := b._SchemaTypeForExpr(base, imports)
	if !ok {
		return nil, false
	}

	typeSpec := builder._TypeSpecs[typeName]
	if typeSpec == nil {
		return nil, false
	}

	return builder._SchemaFromTypeSpecWithArgs(typeName, typeSpec, args, imports), true
}

func (b *_ASTSchemaBuilder) _SchemaTypeForExpr(expr ast.Expr, imports map[string]string) (string, *_ASTSchemaBuilder, bool) {
	switch t := expr.(type) {
	case *ast.Ident:
		if b._TypeSpecs[t.Name] == nil {
			return "", nil, false
		}

		return t.Name, b, true
	case *ast.SelectorExpr:
		return b._SchemaTypeForSelector(t, imports)
	default:
		return "", nil, false
	}
}

func (b *_ASTSchemaBuilder) _SchemaTypeForSelector(expr *ast.SelectorExpr, imports map[string]string) (string, *_ASTSchemaBuilder, bool) {
	if expr == nil || expr.Sel == nil {
		return "", nil, false
	}

	pkg, ok := expr.X.(*ast.Ident)
	if !ok {
		return "", nil, false
	}

	if _, hasImport := imports[pkg.Name]; hasImport {
		imported, ok := b._ImportedBuilderForAlias(pkg.Name, imports)
		if !ok || imported._TypeSpecs[expr.Sel.Name] == nil {
			return "", nil, false
		}

		return expr.Sel.Name, imported, true
	}

	if b._SelectorNamesCurrentPackage(pkg.Name) {
		if b._TypeSpecs[expr.Sel.Name] != nil {
			return expr.Sel.Name, b, true
		}
	}

	return "", nil, false
}

func (b *_ASTSchemaBuilder) _SchemaFromSelectorExpr(expr *ast.SelectorExpr, imports map[string]string) (*Schema, bool) {
	if pkg, ok := expr.X.(*ast.Ident); ok && pkg.Name == "time" && expr.Sel.Name == "Time" && imports[pkg.Name] == "time" {
		return &Schema{Type: "string", Format: "date-time"}, true
	}

	typeName, builder, ok := b._SchemaTypeForSelector(expr, imports)
	if !ok {
		return nil, false
	}

	return builder._SchemaFromTypeSpec(typeName, builder._TypeSpecs[typeName]), true
}

func (b *_ASTSchemaBuilder) _SelectorNamesCurrentPackage(name string) bool {
	if name == "" {
		return false
	}

	return b._SelfAliases[name]
}

func (b *_ASTSchemaBuilder) _SchemaFromTypeSpec(typeName string, typeSpec *ast.TypeSpec) *Schema {
	return b._SchemaFromTypeSpecWithEnv(typeName, typeSpec, nil)
}

func (b *_ASTSchemaBuilder) _SchemaFromTypeSpecWithArgs(typeName string, typeSpec *ast.TypeSpec, args []_ASTSchemaArg, imports map[string]string) *Schema {
	env := b._TypeParamEnv(typeSpec, args, imports)
	componentTypeName := typeName
	if len(args) > 0 {
		componentTypeName += "." + _SchemaExprComponentSuffix(args, imports)
	}

	return b._SchemaFromTypeSpecWithEnv(componentTypeName, typeSpec, env)
}

func (b *_ASTSchemaBuilder) _SchemaFromTypeSpecWithEnv(typeName string, typeSpec *ast.TypeSpec, env map[string]_ASTSchemaArg) *Schema {
	if _, ok := typeSpec.Type.(*ast.StructType); !ok {
		return b._SchemaFromExpr(typeSpec.Type, env, b._TypeSpecImports[typeSpec])
	}

	componentName := b._ComponentName(typeName, typeSpec)
	if componentName == "" {
		return b._SchemaFromExpr(typeSpec.Type, env, b._TypeSpecImports[typeSpec])
	}
	componentName = b._DisambiguatedComponentName(componentName, typeName)

	if _, exists := b._Components[componentName]; exists {
		return &Schema{Ref: "#/components/schemas/" + componentName}
	}

	if b._Visiting[componentName] {
		return &Schema{Ref: "#/components/schemas/" + componentName}
	}

	b._Visiting[componentName] = true
	b._Components[componentName] = &Schema{Type: "object"}
	b._ComponentPkgs[componentName] = b._PkgPath
	b._Components[componentName] = b._SchemaFromExpr(typeSpec.Type, env, b._TypeSpecImports[typeSpec])
	delete(b._Visiting, componentName)

	return &Schema{Ref: "#/components/schemas/" + componentName}
}

func (b *_ASTSchemaBuilder) _SchemaFromExpr(expr ast.Expr, env map[string]_ASTSchemaArg, imports map[string]string) *Schema {
	switch t := expr.(type) {
	case *ast.Ident:
		if env != nil {
			if mapped, ok := env[t.Name]; ok && mapped._Expr != nil {
				if mappedIdent, ok := mapped._Expr.(*ast.Ident); ok && mappedIdent.Name == t.Name {
					return &Schema{}
				}

				return b._SchemaFromExpr(mapped._Expr, env, mapped._Imports)
			}
		}

		if schema := _SchemaFromIdent(t.Name); schema != nil {
			return schema
		}

		if typeSpec := b._TypeSpecs[t.Name]; typeSpec != nil {
			return b._SchemaFromTypeSpec(t.Name, typeSpec)
		}

		return &Schema{}
	case *ast.StarExpr:
		return _NullableSchema(b._SchemaFromExpr(t.X, env, imports))
	case *ast.ArrayType:
		if _IsByteExpr(t.Elt) {
			return &Schema{Type: "string", Format: "byte"}
		}

		return &Schema{Type: "array", Items: b._SchemaFromExpr(t.Elt, env, imports)}
	case *ast.MapType:
		return &Schema{Type: "object", AdditionalProperties: b._SchemaFromExpr(t.Value, env, imports)}
	case *ast.StructType:
		return b._StructSchema(t, env, imports)
	case *ast.InterfaceType:
		return &Schema{}
	case *ast.SelectorExpr:
		if schema, ok := b._SchemaFromSelectorExpr(t, imports); ok {
			return schema
		}

		return &Schema{}
	case *ast.IndexExpr:
		args := _ResolveSchemaArgs([]ast.Expr{t.Index}, env, imports)
		if schema, ok := b._SchemaFromGenericExpr(t.X, args, imports); ok {
			return schema
		}

		return b._SchemaFromExpr(t.X, env, imports)
	case *ast.IndexListExpr:
		args := _ResolveSchemaArgs(t.Indices, env, imports)
		if schema, ok := b._SchemaFromGenericExpr(t.X, args, imports); ok {
			return schema
		}

		return b._SchemaFromExpr(t.X, env, imports)
	default:
		return &Schema{}
	}
}

func (b *_ASTSchemaBuilder) _StructSchema(st *ast.StructType, env map[string]_ASTSchemaArg, imports map[string]string) *Schema {
	props := map[string]*Schema{}
	required := []string{}

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			embedded := b._EmbeddedStructSchema(field.Type, env, imports)
			if embedded != nil {
				for name, schema := range embedded.Properties {
					props[name] = schema
				}

				required = append(required, embedded.Required...)
			}

			continue
		}

		jsonTag, goaiTag := _ASTStructTags(field)
		if jsonTag == "-" {
			continue
		}

		_, omitempty := splitJSONTag(jsonTag, "")
		for _, name := range field.Names {
			if name == nil || !name.IsExported() {
				continue
			}

			propName, fieldOmitempty := splitJSONTag(jsonTag, name.Name)
			fieldSchema := b._SchemaFromExpr(field.Type, env, imports)
			if goaiTag != "" {
				applyGoaiTag(fieldSchema, goaiTag)
			}

			props[propName] = fieldSchema
			if !omitempty && !fieldOmitempty && !_ASTFieldIsPointer(field.Type) {
				required = append(required, propName)
			}
		}
	}

	return &Schema{Type: "object", Properties: props, Required: required}
}

func (b *_ASTSchemaBuilder) _EmbeddedStructSchema(expr ast.Expr, env map[string]_ASTSchemaArg, imports map[string]string) *Schema {
	switch t := expr.(type) {
	case *ast.StructType:
		return b._StructSchema(t, env, imports)
	case *ast.Ident:
		typeSpec := b._TypeSpecs[t.Name]
		if typeSpec == nil {
			return nil
		}

		st, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return nil
		}

		return b._StructSchema(st, env, b._TypeSpecImports[typeSpec])
	default:
		return nil
	}
}

func (b *_ASTSchemaBuilder) _ImportedBuilderForAlias(alias string, imports map[string]string) (*_ASTSchemaBuilder, bool) {
	if alias == "" {
		return nil, false
	}

	importPath := imports[alias]
	if importPath == "" {
		return nil, false
	}

	if imported, ok := b._ImportBuilders[importPath]; ok {
		if imported != nil {
			imported._Imports[alias] = importPath
			imported._SelfAliases[alias] = true
		}

		return imported, imported != nil
	}

	files, dir, ok := b._ImportedPackageFiles(importPath)
	if !ok {
		b._ImportBuilders[importPath] = nil

		return nil, false
	}

	imported := _NewASTSchemaBuilderWithState(
		files,
		importPath,
		b._RootPkgPath,
		dir,
		b._BuildTags,
		nil,
		map[string]bool{alias: true},
		b._Components,
		b._ComponentPkgs,
		b._ComponentOwners,
		b._Visiting,
		b._ImportBuilders,
		b._ImportNames,
	)
	b._ImportBuilders[importPath] = imported
	imported._Imports[alias] = importPath

	return imported, true
}

func (b *_ASTSchemaBuilder) _ImportedPackageFiles(importPath string) ([]*ast.File, string, bool) {
	dir := b._ImportDir(importPath)
	if dir == "" {
		return nil, "", false
	}

	buildCtx := build.Default
	buildCtx.BuildTags = append(append([]string(nil), buildCtx.BuildTags...), b._BuildTags...)
	filter := func(info fs.FileInfo) bool {
		if strings.HasSuffix(info.Name(), "_test.go") {
			return false
		}

		match, err := buildCtx.MatchFile(dir, info.Name())

		return err == nil && match
	}

	pkgs, err := parser.ParseDir(token.NewFileSet(), dir, filter, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		return nil, "", false
	}

	files := _ASTPackageFiles(pkgs)
	if len(files) == 0 {
		return nil, "", false
	}

	return files, dir, true
}

func (b *_ASTSchemaBuilder) _ImportDir(importPath string) string {
	if importDir := _ModuleImportDir(b._Dir, importPath); importDir != "" {
		return importDir
	}

	buildCtx := build.Default
	buildCtx.BuildTags = append(append([]string(nil), buildCtx.BuildTags...), b._BuildTags...)
	if _LooksLikeStandardImport(importPath) {
		if pkg, err := buildCtx.Import(importPath, b._Dir, build.FindOnly); err == nil && pkg.Dir != "" {
			return pkg.Dir
		}

		return ""
	}

	return _GoListImportDir(b._Dir, importPath, b._BuildTags)
}

func _ImportPackageName(importPath string, dir string, buildTags []string, importNames *sync.Map) string {
	if importNames == nil {
		importNames = &sync.Map{}
	}

	importDir := _ModuleImportDir(dir, importPath)
	if importDir == "" && _LooksLikeStandardImport(importPath) {
		buildCtx := build.Default
		buildCtx.BuildTags = append(append([]string(nil), buildCtx.BuildTags...), buildTags...)
		if pkg, err := buildCtx.Import(importPath, dir, build.FindOnly); err == nil && pkg.Dir != "" {
			importDir = pkg.Dir
		}
	}

	cacheKey := importDir + "\x00" + strings.Join(buildTags, "\x00")
	if importDir != "" {
		if cached, ok := importNames.Load(cacheKey); ok {
			if name, ok := cached.(string); ok && name != "" {
				return name
			}
		}

		if name, ok := _ParseImportPackageNameFromDir(importDir, buildTags); ok {
			importNames.Store(cacheKey, name)

			return name
		}
	}

	return _DefaultPackageNameFromImportPath(importPath)
}

func _ParseImportPackageNameFromDir(importDir string, buildTags []string) (string, bool) {
	entries, err := os.ReadDir(importDir)
	if err != nil {
		return "", false
	}

	buildCtx := build.Default
	buildCtx.BuildTags = append(append([]string(nil), buildCtx.BuildTags...), buildTags...)
	for _, entry := range entries {
		info, err := entry.Info()
		if err != nil || info.IsDir() || strings.HasSuffix(info.Name(), "_test.go") {
			continue
		}

		match, err := buildCtx.MatchFile(importDir, info.Name())
		if err != nil || !match {
			continue
		}

		file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(importDir, info.Name()), nil, parser.PackageClauseOnly)
		if err != nil || file == nil || file.Name == nil || file.Name.Name == "" {
			continue
		}

		return file.Name.Name, true
	}

	return "", false
}

func _DefaultPackageNameFromImportPath(importPath string) string {
	base := importpath.Base(importPath)
	if base == "" || base == "." || base == "/" {
		return ""
	}

	if strings.HasPrefix(base, "v") && len(base) > 1 && _AllDigits(base[1:]) {
		parent := importpath.Base(importpath.Dir(importPath))
		if parent != "" && parent != "." && parent != "/" {
			base = parent
		}
	}

	if idx := strings.LastIndex(base, "."); idx > 0 {
		base = base[:idx]
	}

	return base
}

func _AllDigits(s string) bool {
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}

	return s != ""
}

func _LooksLikeStandardImport(importPath string) bool {
	first, _, _ := strings.Cut(importPath, "/")

	return !strings.Contains(first, ".")
}

func _ASTPackageFiles(pkgs map[string]*ast.Package) []*ast.File {
	if len(pkgs) == 0 {
		return nil
	}

	for name, pkg := range pkgs {
		if strings.HasSuffix(name, "_test") {
			continue
		}

		files := make([]*ast.File, 0, len(pkg.Files))
		for _, file := range pkg.Files {
			files = append(files, file)
		}

		return files
	}

	return nil
}

func _ASTPackageName(files []*ast.File) string {
	for _, file := range files {
		if file.Name != nil {
			return file.Name.Name
		}
	}

	return ""
}

func _ModuleImportDir(startDir string, importPath string) string {
	if startDir == "" || importPath == "" {
		return ""
	}

	dir := startDir
	for {
		goModPath := filepath.Join(dir, "go.mod")
		data, err := os.ReadFile(goModPath)
		if err == nil {
			return _ModuleImportDirFromGoMod(dir, string(data), importPath)
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}

		dir = parent
	}
}

func _ModuleImportDirFromGoMod(moduleDir string, goMod string, importPath string) string {
	for _, line := range strings.Split(goMod, "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 || fields[0] != "module" {
			continue
		}

		modulePath := fields[1]
		if importPath != modulePath && !strings.HasPrefix(importPath, modulePath+"/") {
			return ""
		}

		rel := strings.TrimPrefix(importPath, modulePath)
		rel = strings.TrimPrefix(rel, "/")
		dir := filepath.Join(moduleDir, filepath.FromSlash(rel))
		if info, err := os.Stat(dir); err == nil && info.IsDir() {
			return dir
		}

		return ""
	}

	return ""
}

func _GoListImportDir(workDir string, importPath string, buildTags []string) string {
	if importPath == "" {
		return ""
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	args := []string{"list", "-f", "{{.Dir}}"}
	if len(buildTags) > 0 {
		args = append(args, "-tags", strings.Join(buildTags, ","))
	}
	args = append(args, importPath)

	cmd := exec.CommandContext(ctx, "go", args...)
	if workDir != "" {
		cmd.Dir = workDir
	}

	out, err := cmd.Output()
	if err != nil {
		return ""
	}

	dir := strings.TrimSpace(string(out))
	if info, err := os.Stat(dir); err == nil && info.IsDir() {
		return dir
	}

	return ""
}

func (b *_ASTSchemaBuilder) _TypeParamEnv(typeSpec *ast.TypeSpec, args []_ASTSchemaArg, imports map[string]string) map[string]_ASTSchemaArg {
	if typeSpec == nil || typeSpec.TypeParams == nil || len(args) == 0 {
		return nil
	}

	env := map[string]_ASTSchemaArg{}
	argIndex := 0
	for _, field := range typeSpec.TypeParams.List {
		for _, name := range field.Names {
			if argIndex >= len(args) {
				return env
			}

			arg := args[argIndex]
			if arg._Imports == nil {
				arg._Imports = imports
			}
			env[name.Name] = arg
			argIndex++
		}
	}

	return env
}

func _SchemaArgs(args []ast.Expr, imports map[string]string) []_ASTSchemaArg {
	out := make([]_ASTSchemaArg, 0, len(args))
	for _, arg := range args {
		out = append(out, _ASTSchemaArg{_Expr: arg, _Imports: imports})
	}

	return out
}

func _ResolveSchemaArgs(args []ast.Expr, env map[string]_ASTSchemaArg, imports map[string]string) []_ASTSchemaArg {
	if len(args) == 0 {
		return nil
	}

	if len(env) == 0 {
		return _SchemaArgs(args, imports)
	}

	out := make([]_ASTSchemaArg, 0, len(args))
	for _, arg := range args {
		out = append(out, _ResolveSchemaArg(arg, env, imports))
	}

	return out
}

func _ResolveSchemaArg(expr ast.Expr, env map[string]_ASTSchemaArg, imports map[string]string) _ASTSchemaArg {
	switch t := expr.(type) {
	case *ast.Ident:
		mapped, ok := env[t.Name]
		if !ok || mapped._Expr == nil {
			return _ASTSchemaArg{_Expr: expr, _Imports: imports}
		}

		if mappedIdent, ok := mapped._Expr.(*ast.Ident); ok && mappedIdent.Name == t.Name {
			return _ASTSchemaArg{_Expr: expr, _Imports: imports}
		}

		return _ResolveSchemaArg(mapped._Expr, env, mapped._Imports)
	case *ast.StarExpr:
		inner := _ResolveSchemaArg(t.X, env, imports)

		return _ASTSchemaArg{_Expr: &ast.StarExpr{X: inner._Expr}, _Imports: inner._Imports}
	case *ast.ArrayType:
		inner := _ResolveSchemaArg(t.Elt, env, imports)

		return _ASTSchemaArg{_Expr: &ast.ArrayType{Elt: inner._Expr}, _Imports: inner._Imports}
	case *ast.MapType:
		key := _ResolveSchemaArg(t.Key, env, imports)
		value := _ResolveSchemaArg(t.Value, env, imports)

		return _ASTSchemaArg{
			_Expr: &ast.MapType{
				Key:   key._Expr,
				Value: value._Expr,
			},
			_Imports: value._Imports,
		}
	case *ast.IndexExpr:
		x := _ResolveSchemaArg(t.X, env, imports)
		index := _ResolveSchemaArg(t.Index, env, imports)

		return _ASTSchemaArg{
			_Expr: &ast.IndexExpr{
				X:     x._Expr,
				Index: index._Expr,
			},
			_Imports: index._Imports,
		}
	case *ast.IndexListExpr:
		indices := make([]ast.Expr, 0, len(t.Indices))
		argImports := imports
		for _, idx := range t.Indices {
			arg := _ResolveSchemaArg(idx, env, imports)
			indices = append(indices, arg._Expr)
			argImports = arg._Imports
		}

		x := _ResolveSchemaArg(t.X, env, imports)

		return _ASTSchemaArg{
			_Expr: &ast.IndexListExpr{
				X:       x._Expr,
				Indices: indices,
			},
			_Imports: argImports,
		}
	default:
		return _ASTSchemaArg{_Expr: expr, _Imports: imports}
	}
}

func _SchemaExprComponentSuffix(args []_ASTSchemaArg, imports map[string]string) string {
	parts := make([]string, 0, len(args))
	for _, arg := range args {
		argImports := arg._Imports
		if argImports == nil {
			argImports = imports
		}

		parts = append(parts, _SanitizeComponentName(_SchemaExprName(arg._Expr, argImports)))
	}

	return strings.Join(parts, ".")
}

func _SchemaExprName(expr ast.Expr, imports map[string]string) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		if pkg, ok := t.X.(*ast.Ident); ok {
			if importPath := imports[pkg.Name]; importPath != "" {
				return strings.ReplaceAll(importPath, "/", ".") + "." + t.Sel.Name
			}
		}

		return _SchemaExprName(t.X, imports) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "ptr." + _SchemaExprName(t.X, imports)
	case *ast.ArrayType:
		return "array." + _SchemaExprName(t.Elt, imports)
	case *ast.IndexExpr:
		return _SchemaExprName(t.X, imports) + "." + _SchemaExprName(t.Index, imports)
	case *ast.IndexListExpr:
		parts := make([]string, 0, len(t.Indices)+1)
		parts = append(parts, _SchemaExprName(t.X, imports))
		for _, idx := range t.Indices {
			parts = append(parts, _SchemaExprName(idx, imports))
		}

		return strings.Join(parts, ".")
	default:
		return "type"
	}
}

func _SanitizeComponentName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '.' || r == '_' || r == '-' {
			b.WriteRune(r)

			continue
		}

		b.WriteByte('_')
	}

	return b.String()
}

func (b *_ASTSchemaBuilder) _ComponentName(typeName string, typeSpec *ast.TypeSpec) string {
	if typeName == "" {
		return ""
	}

	if name := b._CustomComponentName(typeName, typeSpec); name != "" {
		return name
	}

	if b._PkgPath == "" {
		return typeName
	}

	name := shortPkgName(b._PkgPath) + "." + typeName
	if b._RootPkgPath != "" && b._PkgPath != b._RootPkgPath {
		return _FullOperationDocSchemaComponentName(name, b._PkgPath)
	}

	return name
}

func (b *_ASTSchemaBuilder) _CustomComponentName(typeName string, typeSpec *ast.TypeSpec) string {
	name := b._TypeSpecNames[typeSpec]
	if name == "" {
		return ""
	}

	if typeSpec == nil || typeSpec.Name == nil {
		return name
	}

	suffix := ""
	baseName := typeSpec.Name.Name
	if typeName != baseName && strings.HasPrefix(typeName, baseName+".") {
		suffix = strings.TrimPrefix(typeName, baseName)
	}

	return name + suffix
}

func (b *_ASTSchemaBuilder) _DisambiguatedComponentName(name string, typeName string) string {
	owner := b._PkgPath + "\x00" + typeName
	if existing, ok := b._ComponentOwners[name]; !ok || existing == owner {
		b._ComponentOwners[name] = owner

		return name
	}

	full := strings.ReplaceAll(b._PkgPath, "/", ".") + "." + typeName
	b._ComponentOwners[full] = owner

	return full
}

func _SchemaFromIdent(name string) *Schema {
	switch name {
	case "bool":
		return &Schema{Type: "boolean"}
	case "int", "int8", "int16", "int32", "uint", "uint8", "uint16", "uint32":
		return &Schema{Type: "integer", Format: "int32"}
	case "int64", "uint64":
		return &Schema{Type: "integer", Format: "int64"}
	case "float32":
		return &Schema{Type: "number", Format: "float"}
	case "float64":
		return &Schema{Type: "number", Format: "double"}
	case "string":
		return &Schema{Type: "string"}
	case "any":
		return &Schema{}
	default:
		return nil
	}
}

func _NullableSchema(schema *Schema) *Schema {
	if schema == nil {
		return nil
	}

	if schema.Ref != "" {
		return &Schema{
			Nullable: true,
			AllOf:    []*Schema{schema},
		}
	}

	copySchema := *schema
	copySchema.Nullable = true

	return &copySchema
}

func _IsByteExpr(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return false
	}

	return ident.Name == "byte" || ident.Name == "uint8"
}

func _ASTStructTags(field *ast.Field) (string, string) {
	if field == nil || field.Tag == nil {
		return "", ""
	}

	raw, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return "", ""
	}

	tag := reflect.StructTag(raw)

	return tag.Get("json"), tag.Get("goai")
}

func _ASTFieldIsPointer(expr ast.Expr) bool {
	_, ok := expr.(*ast.StarExpr)

	return ok
}

func _EnsureResponse(op *Operation, status string) *Response {
	if op.Responses == nil {
		op.Responses = map[string]*Response{}
	}

	resp := op.Responses[status]
	if resp == nil {
		resp = &Response{}
		op.Responses[status] = resp
	}

	return resp
}

func _EnsureOperationParameter(op *Operation, in, name string) *Parameter {
	param := _FindOperationParameter(op.Parameters, in, name)
	if param == nil {
		param = &Parameter{In: in, Name: name}
		op.Parameters = append(op.Parameters, param)
	}

	return param
}

func _EnsureHeader(resp *Response, name string) *Header {
	if resp.Headers == nil {
		resp.Headers = map[string]*Header{}
	}

	header := resp.Headers[name]
	if header == nil {
		header = &Header{}
		resp.Headers[name] = header
	}

	return header
}

func _EnsureLink(resp *Response, name string) *Link {
	if resp.Links == nil {
		resp.Links = map[string]*Link{}
	}

	link := resp.Links[name]
	if link == nil {
		link = &Link{}
		resp.Links[name] = link
	}

	return link
}

func _EnsureServer(op *Operation, url string) *Server {
	for i := range op.Servers {
		if op.Servers[i].URL == url {
			return &op.Servers[i]
		}
	}

	op.Servers = append(op.Servers, Server{URL: url})

	return &op.Servers[len(op.Servers)-1]
}

func _EnsureResponseMediaType(resp *Response, mediaType string) *MediaType {
	if mediaType == "" {
		mediaType = "application/json"
	}

	if resp.Content == nil {
		resp.Content = map[string]*MediaType{}
	}

	mt := resp.Content[mediaType]
	if mt == nil {
		mt = &MediaType{}
		resp.Content[mediaType] = mt
	}

	return mt
}

func _EnsureRequestMediaType(body *RequestBody, mediaType string) *MediaType {
	if mediaType == "" {
		mediaType = "application/json"
	}

	if body.Content == nil {
		body.Content = map[string]*MediaType{}
	}

	mt := body.Content[mediaType]
	if mt == nil {
		mt = &MediaType{}
		body.Content[mediaType] = mt
	}

	return mt
}

func _RequiredToken(token string) bool {
	switch strings.ToLower(token) {
	case "required", "true", "yes":
		return true
	default:
		return false
	}
}

func _BoolOption(opts map[string]string, key string) bool {
	raw, ok := opts[key]
	if !ok {
		return false
	}

	return _ParseBool(raw)
}

func _ParseBool(raw string) bool {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "", "true", "yes", "1", "required":
		return true
	default:
		return false
	}
}

func _ParseValue(raw string) any {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return ""
	}

	var v any
	if err := json.Unmarshal([]byte(raw), &v); err == nil {
		return v
	}

	if f, err := strconv.ParseFloat(raw, 64); err == nil {
		return f
	}

	return raw
}

func _DecodeStructured(raw string, dst any) bool {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return false
	}

	if err := yaml.Unmarshal([]byte(raw), dst); err == nil {
		return true
	}

	return json.Unmarshal([]byte(raw), dst) == nil
}

func _BuildTagsFromGOFLAGS() []string {
	fields := _SplitDirectiveFields(os.Getenv("GOFLAGS"))
	out := []string{}
	for i := 0; i < len(fields); i++ {
		field := fields[i]
		if field == "-tags" && i+1 < len(fields) {
			out = append(out, _SplitBuildTags(fields[i+1])...)
			i++

			continue
		}

		if tags, ok := strings.CutPrefix(field, "-tags="); ok {
			out = append(out, _SplitBuildTags(tags)...)
		}
	}

	return out
}

func _SplitBuildTags(raw string) []string {
	raw = strings.ReplaceAll(raw, ",", " ")
	fields := strings.Fields(raw)
	out := make([]string, 0, len(fields))
	for _, field := range fields {
		field = strings.TrimSpace(field)
		if field != "" {
			out = append(out, field)
		}
	}

	return out
}

func _MergeBuildTags(groups ...[]string) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, group := range groups {
		for _, tag := range group {
			tag = strings.TrimSpace(tag)
			if tag == "" || seen[tag] {
				continue
			}

			seen[tag] = true
			out = append(out, tag)
		}
	}

	return out
}

func _Contains(fields []string, value string) bool {
	for _, f := range fields {
		if f == value {
			return true
		}
	}

	return false
}

func _TakeFirstField(s string) (string, string) {
	fields := _SplitDirectiveFields(s)
	if len(fields) == 0 {
		return "", ""
	}

	first := fields[0]
	idx := strings.Index(s, first)
	if idx < 0 {
		return first, ""
	}

	return first, strings.TrimSpace(s[idx+len(first):])
}

func _SplitDirectiveFields(s string) []string {
	var fields []string
	var b strings.Builder
	quote := rune(0)
	escaped := false
	jsonDepth := 0
	jsonString := false
	jsonEscaped := false

	for _, r := range s {
		if jsonDepth > 0 {
			b.WriteRune(r)
			if jsonEscaped {
				jsonEscaped = false

				continue
			}

			if jsonString {
				switch r {
				case '\\':
					jsonEscaped = true
				case '"':
					jsonString = false
				}

				continue
			}

			switch r {
			case '"':
				jsonString = true
			case '{', '[':
				jsonDepth++
			case '}', ']':
				jsonDepth--
			}

			continue
		}

		if escaped {
			b.WriteRune(r)
			escaped = false

			continue
		}

		if quote != 0 {
			if r == '\\' {
				escaped = true

				continue
			}

			if r == quote {
				quote = 0

				continue
			}

			b.WriteRune(r)

			continue
		}

		switch r {
		case '\'', '"':
			if b.Len() == 0 {
				quote = r
			} else {
				b.WriteRune(r)
			}
		case '{', '[':
			jsonDepth = 1
			b.WriteRune(r)
		case ' ', '\t', '\n', '\r':
			if b.Len() > 0 {
				fields = append(fields, b.String())
				b.Reset()
			}
		default:
			b.WriteRune(r)
		}
	}

	if b.Len() > 0 {
		fields = append(fields, b.String())
	}

	return fields
}
