package goai

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

// Merge3Way overlays an auto-generated OpenAPI document onto a hand-tuned
// existing document, preserving the hand-tuned content as the source of
// truth.
//
// Merge policy:
//   - Top-level scalars/maps (openapi, info, servers, security) are taken
//     verbatim from `existing` when present. The hand-tuned document is the
//     canonical author of prose and metadata.
//   - `tags`: union — every tag in `existing` is kept in its original order,
//     then any tag in `generated` whose name is missing from `existing` is
//     appended.
//   - `paths`: per-path union — every path in `existing` is kept verbatim
//     (including hand-curated descriptions, parameters, examples, $refs).
//     Any path present in `generated` but missing from `existing` is
//     appended at the end of the paths map, so routes discovered in source
//     code surface in the spec automatically without disturbing the
//     hand-tuned prose for existing routes.
//   - `components.*`: per-name union for every sub-map defined by
//     OpenAPI 3.0.3 — schemas, responses, parameters, examples,
//     requestBodies, headers, securitySchemes, links, callbacks.
//     Existing entries always win; generated entries fill gaps only.
//     Hand-tuned schema $refs always remain wired correctly.
//
// When `existing` is empty, the generated bytes are returned unchanged so
// the caller does not have to special-case "no baseline yet".
func Merge3Way(generated, existing, overrides []byte) ([]byte, error) {
	_ = overrides

	if len(existing) == 0 {
		return generated, nil
	}

	if len(generated) == 0 {
		return existing, nil
	}

	var existingDoc, generatedDoc yaml.Node
	if err := yaml.Unmarshal(existing, &existingDoc); err != nil {
		return nil, fmt.Errorf("goai: parse existing yaml: %w", err)
	}

	if err := yaml.Unmarshal(generated, &generatedDoc); err != nil {
		return nil, fmt.Errorf("goai: parse generated yaml: %w", err)
	}

	existingRoot := documentRoot(&existingDoc)
	generatedRoot := documentRoot(&generatedDoc)
	if existingRoot == nil || existingRoot.Kind != yaml.MappingNode {
		return generated, nil
	}

	if generatedRoot == nil || generatedRoot.Kind != yaml.MappingNode {
		return existing, nil
	}

	mergeTags(existingRoot, generatedRoot)
	mergePaths(existingRoot, generatedRoot)
	mergeComponents(existingRoot, generatedRoot)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&existingDoc); err != nil {
		_ = enc.Close()

		return nil, fmt.Errorf("goai: emit merged yaml: %w", err)
	}

	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("goai: close merged emitter: %w", err)
	}

	return buf.Bytes(), nil
}

// documentRoot returns the inner mapping node of a yaml.Node tree as
// produced by yaml.Unmarshal. Top-level Unmarshal yields a DocumentNode
// whose first Content entry is the actual root.
func documentRoot(n *yaml.Node) *yaml.Node {
	if n == nil {
		return nil
	}

	if n.Kind == yaml.DocumentNode {
		if len(n.Content) == 0 {
			return nil
		}

		return n.Content[0]
	}

	return n
}

// mappingValue looks up the value node for a string key inside a mapping
// node. Returns nil when the key is absent or the parent is not a mapping.
func mappingValue(parent *yaml.Node, key string) *yaml.Node {
	if parent == nil || parent.Kind != yaml.MappingNode {
		return nil
	}

	for i := 0; i+1 < len(parent.Content); i += 2 {
		if parent.Content[i].Value == key {
			return parent.Content[i+1]
		}
	}

	return nil
}

// mappingSet stores a (key, value) pair into a mapping node, replacing the
// existing pair when key is present, otherwise appending.
func mappingSet(parent *yaml.Node, keyNode, valueNode *yaml.Node) {
	if parent == nil || parent.Kind != yaml.MappingNode {
		return
	}

	for i := 0; i+1 < len(parent.Content); i += 2 {
		if parent.Content[i].Value == keyNode.Value {
			parent.Content[i+1] = valueNode

			return
		}
	}

	parent.Content = append(parent.Content, keyNode, valueNode)
}

// mappingKeys returns the set of string keys present in a mapping node.
func mappingKeys(n *yaml.Node) map[string]bool {
	out := map[string]bool{}
	if n == nil || n.Kind != yaml.MappingNode {
		return out
	}

	for i := 0; i+1 < len(n.Content); i += 2 {
		out[n.Content[i].Value] = true
	}

	return out
}

// mergePaths appends every path in the generated paths map that is not
// already present in the existing paths map, and fills in the
// auto-detected security requirement on existing operations that did not
// declare one. Hand-tuned content (summary, description, examples, etc.)
// is left untouched.
//
// The security fill-in matters because the auto-discovered acceptance
// chain is the authoritative source of truth for what authentication
// scheme each operation actually enforces; without this step, an
// operation that the hand-tuned base spec did not bother to annotate
// would inherit the document-level GlobalSecurity (typically OAuth2),
// which can mislabel admin / internal / app-token endpoints.
func mergePaths(existingRoot, generatedRoot *yaml.Node) {
	existingPaths := mappingValue(existingRoot, "paths")
	generatedPaths := mappingValue(generatedRoot, "paths")
	if generatedPaths == nil || generatedPaths.Kind != yaml.MappingNode {
		return
	}

	if existingPaths == nil {
		// Existing has no paths section at all — splice the generated one in.
		mappingSet(existingRoot, &yaml.Node{Kind: yaml.ScalarNode, Value: "paths"}, generatedPaths)

		return
	}

	if existingPaths.Kind != yaml.MappingNode {
		return
	}

	existingPathByKey := map[string]*yaml.Node{}
	for i := 0; i+1 < len(existingPaths.Content); i += 2 {
		existingPathByKey[existingPaths.Content[i].Value] = existingPaths.Content[i+1]
	}

	for i := 0; i+1 < len(generatedPaths.Content); i += 2 {
		key := generatedPaths.Content[i].Value
		generatedPathItem := generatedPaths.Content[i+1]
		if existingItem, ok := existingPathByKey[key]; ok {
			fillOperationSecurity(existingItem, generatedPathItem)

			continue
		}

		existingPaths.Content = append(existingPaths.Content,
			generatedPaths.Content[i],
			generatedPathItem)
	}
}

// fillOperationSecurity copies the generated security node onto each
// operation in the existing path item that does not already declare its
// own. Operations the generator did not touch (e.g. a leaf method
// documented only in the hand-tuned spec) are left alone, and existing
// security entries always win — this is a fill-in, not an override.
//
// Recognised HTTP method keys mirror PathItem fields (get/put/post/...).
func fillOperationSecurity(existingItem, generatedItem *yaml.Node) {
	if existingItem == nil || generatedItem == nil {
		return
	}

	if existingItem.Kind != yaml.MappingNode || generatedItem.Kind != yaml.MappingNode {
		return
	}

	httpVerbs := map[string]struct{}{
		"get": {}, "put": {}, "post": {}, "delete": {},
		"options": {}, "head": {}, "patch": {}, "trace": {},
	}

	generatedOps := map[string]*yaml.Node{}
	for i := 0; i+1 < len(generatedItem.Content); i += 2 {
		key := generatedItem.Content[i].Value
		if _, ok := httpVerbs[key]; !ok {
			continue
		}

		generatedOps[key] = generatedItem.Content[i+1]
	}

	for i := 0; i+1 < len(existingItem.Content); i += 2 {
		key := existingItem.Content[i].Value
		if _, ok := httpVerbs[key]; !ok {
			continue
		}

		generatedOp, ok := generatedOps[key]
		if !ok {
			continue
		}

		existingOp := existingItem.Content[i+1]
		if existingOp == nil || existingOp.Kind != yaml.MappingNode {
			continue
		}

		if generatedOp == nil || generatedOp.Kind != yaml.MappingNode {
			continue
		}

		// Only copy security when existing operation does not have one.
		// `security: []` (explicit override) and `security: [{...}]`
		// (existing requirements) both mean "hand-tuned wins".
		if mappingValue(existingOp, "security") != nil {
			continue
		}

		generatedSecurity := mappingValue(generatedOp, "security")
		if generatedSecurity == nil {
			continue
		}

		mappingSet(existingOp, &yaml.Node{Kind: yaml.ScalarNode, Value: "security"}, generatedSecurity)
	}
}

// mergeTags appends every tag in the generated tags sequence whose `name`
// is missing from the existing tags sequence. Existing tag order is
// preserved.
func mergeTags(existingRoot, generatedRoot *yaml.Node) {
	existingTags := mappingValue(existingRoot, "tags")
	generatedTags := mappingValue(generatedRoot, "tags")
	if generatedTags == nil || generatedTags.Kind != yaml.SequenceNode {
		return
	}

	if existingTags == nil {
		mappingSet(existingRoot, &yaml.Node{Kind: yaml.ScalarNode, Value: "tags"}, generatedTags)

		return
	}

	if existingTags.Kind != yaml.SequenceNode {
		return
	}

	existingNames := map[string]bool{}
	for _, child := range existingTags.Content {
		if child.Kind != yaml.MappingNode {
			continue
		}

		if name := mappingValue(child, "name"); name != nil {
			existingNames[name.Value] = true
		}
	}

	for _, child := range generatedTags.Content {
		if child.Kind != yaml.MappingNode {
			continue
		}

		name := mappingValue(child, "name")
		if name == nil || existingNames[name.Value] {
			continue
		}

		existingTags.Content = append(existingTags.Content, child)
	}
}

// mergeComponents merges schemas + securitySchemes inside components.
// Existing entries always win; generated entries fill gaps only.
func mergeComponents(existingRoot, generatedRoot *yaml.Node) {
	generatedComponents := mappingValue(generatedRoot, "components")
	if generatedComponents == nil || generatedComponents.Kind != yaml.MappingNode {
		return
	}

	existingComponents := mappingValue(existingRoot, "components")
	if existingComponents == nil {
		mappingSet(existingRoot, &yaml.Node{Kind: yaml.ScalarNode, Value: "components"}, generatedComponents)

		return
	}

	if existingComponents.Kind != yaml.MappingNode {
		return
	}

	for _, sub := range []string{
		"schemas",
		"responses",
		"parameters",
		"examples",
		"requestBodies",
		"headers",
		"securitySchemes",
		"links",
		"callbacks",
	} {
		mergeSubMap(existingComponents, generatedComponents, sub)
	}
}

// mergeSubMap appends entries from generated[parentKey] that are missing
// from existing[parentKey]. Existing entries are left intact.
func mergeSubMap(existingParent, generatedParent *yaml.Node, key string) {
	generatedMap := mappingValue(generatedParent, key)
	if generatedMap == nil || generatedMap.Kind != yaml.MappingNode {
		return
	}

	existingMap := mappingValue(existingParent, key)
	if existingMap == nil {
		mappingSet(existingParent, &yaml.Node{Kind: yaml.ScalarNode, Value: key}, generatedMap)

		return
	}

	if existingMap.Kind != yaml.MappingNode {
		return
	}

	existingKeys := mappingKeys(existingMap)
	for i := 0; i+1 < len(generatedMap.Content); i += 2 {
		k := generatedMap.Content[i].Value
		if existingKeys[k] {
			continue
		}

		existingMap.Content = append(existingMap.Content,
			generatedMap.Content[i],
			generatedMap.Content[i+1])
	}
}
